### ISSUE TITLE
Multisite Support

### ISSUE THREAD

**Issue by slamkajs** [EnhancedAthlete/EA-WP-AWS-SES-Bounce-Handler#7]
This plugin would be great if it could work in a Multisite environment.

**Comment by slamkajs** [comment]
Turns out this was a complication with plugin interactions.

**Comment by BrianHenryIE** [comment]
You should use https://github.com/BrianHenryIE/bh-wp-aws-ses-bounce-handler/releases

**Comment by slamkajs** [comment]
Thank you for a more up to date version.  One multisite issue I did find was network activation doesn't install the option into each site.
